### PR TITLE
Making Function to Return Emoji Name

### PR DESCRIPTION
**Pull request by bigsbug**
Making Function to Return Emoji Name 

print(find_name('This is a message with emojis 😄 🐍',**True** )) #return a list is True :  
result :  **['smile', 'snake']**

print(find_name('This is a message with emojis 😄 🐍',**False**)) #return a list is False :
result : **This is a message with emojis smile snake**

### CODE REVIEW

**Comment by bigsbug** [comment]
> 
> 
> [Coverage Status](https://coveralls.io/builds/26449207)
> 
> Coverage remained the same at 100.0% when pulling **[bb366d4](https://github.com/alexmick/emoji-data-python/commit/bb366d4a0d76211939e6dbf8c6038a080f392ecb) on bigsbug:find_name_emoji** into **[0ebf5f2](https://github.com/alexmick/emoji-data-python/commit/0ebf5f27920bb737ca98acee228e37819874a3df) on alexmick:master**.

**Comment by bigsbug** [comment]
> 
> 
> > [Coverage Status](https://coveralls.io/builds/26449207)
> > Coverage remained the same at 100.0% when pulling **[bb366d4](https://github.com/alexmick/emoji-data-python/commit/bb366d4a0d76211939e6dbf8c6038a080f392ecb) on bigsbug:find_name_emoji** into **[0ebf5f2](https://github.com/alexmick/emoji-data-python/commit/0ebf5f27920bb737ca98acee228e37819874a3df) on alexmick:master**.

**Comment by bigsbug** [comment]
what?

**Comment by alexmick** [comment]
Thanks for the contribution as an attempt to resolve #4 .
Unfortunately, the goal of this repo is to avoid external dependency on other libraries (in this case `emoji`).

Closing this to continue the discussion on the issue

**Pull request closed without merging**
